openapi: 3.1.0
info:
  title: Finnhub GPT Actions
  version: 5.0.0
servers:
  - url: https://finnhub.io/api/v1
paths:
  /quote:
    get:
      operationId: getQuote
      summary: Get real-time quote
      parameters:
        - name: symbol
          in: query
          required: true
          schema: { type: string }
      responses:
        '200':
          description: Quote data
          content:
            application/json:
              schema:
                type: object
                properties:
                  c: { type: number }
                  pc: { type: number }
                  h: { type: number }
                  l: { type: number }
                  o: { type: number }
                  v: { type: number }
                  t: { type: integer }
  /stock/candle:
    get:
      operationId: getCandles
      summary: Historical daily OHLCV
      parameters:
        - name: symbol
          in: query
          required: true
          schema: { type: string }
        - name: resolution
          in: query
          required: true
          schema:
            type: string
            enum: [D]
        - name: from
          in: query
          required: true
          schema: { type: integer }
        - name: to
          in: query
          required: true
          schema: { type: integer }
      responses:
        '200':
          description: Daily candles
          content:
            application/json:
              schema:
                type: object
                properties:
                  c: { type: array, items: { type: number } }
                  h: { type: array, items: { type: number } }
                  l: { type: array, items: { type: number } }
                  o: { type: array, items: { type: number } }
                  v: { type: array, items: { type: number } }
                  t: { type: array, items: { type: integer } }
                  s: { type: string }
