openapi: 3.1.0
info:
  title: Finnhub GPT Actions (forced token param)
  version: 4.0.0
  description: Minimal spec that forces the Finnhub API key to be sent as a required query parameter so the builder cannot drop it.
servers:
  - url: https://finnhub.io/api/v1
paths:
  /quote:
    get:
      operationId: getQuote
      summary: Get real-time quote
      parameters:
        - name: symbol
          in: query
          required: true
          schema: { type: string }
        - name: token
          in: query
          required: true
          description: "Finnhub API key – do not change"
          schema:
            type: string
            default: YOUR_WORKING_KEY_HERE
      responses:
        '200':
          description: Quote data
          content:
            application/json:
              schema:
                type: object
                properties:
                  c: { type: number, description: Current price }
                  pc: { type: number, description: Previous close }
                  h: { type: number }
                  l: { type: number }
                  o: { type: number }
                  v: { type: number, description: Volume }
                  t: { type: integer, description: Unix timestamp }
  /stock/candle:
    get:
      operationId: getCandles
      summary: Historical daily OHLCV
      parameters:
        - name: symbol
          in: query
          required: true
          schema: { type: string }
        - name: resolution
          in: query
          required: true
          schema:
            type: string
            enum: [D]
        - name: from
          in: query
          required: true
          schema: { type: integer, description: Unix timestamp (UTC) }
        - name: to
          in: query
          required: true
          schema: { type: integer, description: Unix timestamp (UTC) }
        - name: token
          in: query
          required: true
          description: "Finnhub API key – do not change"
          schema:
            type: string
            default: YOUR_WORKING_KEY_HERE
      responses:
        '200':
          description: Daily candles
          content:
            application/json:
              schema:
                type: object
                properties:
                  c: { type: array, items: { type: number } }   # close
                  h: { type: array, items: { type: number } }
                  l: { type: array, items: { type: number } }
                  o: { type: array, items: { type: number } }
                  v: { type: array, items: { type: number } }
                  t: { type: array, items: { type: integer } }
                  s: { type: string }
