openapi: 3.1.0
info:
  title: Finnhub GPT Actions
  description: >
    Combined endpoints for confirmCandidates and finalCheck actions. Uses only free-tier Finnhub endpoints.
  version: 2.0.0
servers:
  - url: https://finnhub.io/api/v1
    description: Finnhub main API
paths:
  /stock/candle:
    get:
      operationId: getCandles
      summary: Get historical daily OHLCV data
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
        - name: resolution
          in: query
          required: true
          schema:
            type: string
            enum: [D]
            default: D
        - name: from
          in: query
          required: true
          schema:
            type: integer
            description: Unix timestamp (UTC)
        - name: to
          in: query
          required: true
          schema:
            type: integer
            description: Unix timestamp (UTC)
      responses:
        '200':
          description: Daily candle data
          content:
            application/json:
              schema:
                type: object
                properties:
                  c:
                    type: array
                    items: { type: number }
                  h:
                    type: array
                    items: { type: number }
                  l:
                    type: array
                    items: { type: number }
                  o:
                    type: array
                    items: { type: number }
                  v:
                    type: array
                    items: { type: number }
                  t:
                    type: array
                    items: { type: integer }
                  s:
                    type: string
  /calendar/earnings:
    get:
      operationId: getEarningsCalendar
      summary: Get earnings calendar data
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: symbol
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Earnings calendar
          content:
            application/json:
              schema:
                type: object
                properties:
                  earningsCalendar:
                    type: array
                    items:
                      type: object
                      properties:
                        symbol:
                          type: string
                        date:
                          type: string
                          format: date
                        hour:
                          type: string
                        epsEstimate:
                          type: number
                        revenueEstimate:
                          type: number
  /news-sentiment:
    get:
      operationId: getSentiment
      summary: Get 7-day news sentiment for a stock
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: News sentiment data
          content:
            application/json:
              schema:
                type: object
                properties:
                  sentiment:
                    type: string
                  companyNewsScore:
                    type: number
                  buzz:
                    type: object
                    properties:
                      articlesInLastWeek:
                        type: integer
                      buzz:
                        type: number
  /stock/metric:
    get:
      operationId: getStockMetrics
      summary: Get basic fundamental metrics
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
        - name: metric
          in: query
          required: false
          schema:
            type: string
            example: all
      responses:
        '200':
          description: Stock metric data
          content:
            application/json:
              schema:
                type: object
                properties:
                  metric:
                    type: object
                    properties:
                      peNormalizedAnnual:
                        type: number
                      epsGrowth:
                        type: number
  /quote:
    get:
      operationId: getQuote
      summary: Get real-time quote and volume data
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Real-time quote
          content:
            application/json:
              schema:
                type: object
                properties:
                  c:
                    type: number
                  pc:
                    type: number
                  h:
                    type: number
                  l:
                    type: number
                  t:
                    type: integer
                  v:
                    type: number
  /company-news:
    get:
      operationId: getRecentNews
      summary: Get company news headlines from last 24–48 hours
      parameters:
        - name: symbol
          in: query
          required: true
          schema:
            type: string
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: Recent company news
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    datetime:
                      type: integer
                    headline:
                      type: string
                    summary:
                      type: string
                    source:
                      type: string
                    url:
                      type: string
security:
  - finnhubApiKey: []
components:
  securitySchemes:
    finnhubApiKey:
      type: apiKey
      in: query
      name: token
